UMC-Archive/Back

src/controllers/user.controller.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
#️⃣연관된 이슈
유저 정보 불러오는 api
유저 정보를 불러오는 api 생성
토큰은 추후 추가 예정
💬리뷰 요구사항
=> 유저 정보 불러오는 api

src/controllers/user.controller.js, src/dtos/user.dto.js, src/errors.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
Add changeProfileImage api
& api 명세서와 동일화 작업
#️⃣연관된 이슈
#8 changeProfileImage api
📝 유저의 프로필 사진 변경하는 api
[사용 전]
[사용 후]
💬리뷰 요구사항
=> Add changeProfileImage api

src/controllers/user.controller.js, src/dtos/user.dto.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
fix userInfo api & add ChangeGenre
#️⃣연관된 이슈
#12 fix userInfo api & add ChangeGenre
📝유저의 name과 email을 값을 이용해 해당 유저의 장르 번호를 바꾸는 api
[사용 전]
치멘4의 userId -> 4
genreId -> 1
[사용 후]
치멘4의 userId -> 4
genreId -> 2
기존의 userInfo api가 제대로 실행되고 있지 않은 것을 파악 후에
수정함
-> 이유는 bigint가 javascript에서 2이면 2n이 되고 3이면 3n이 되기 때문에
-> 그에 맞게 수정함.
💬리뷰 요구사항
=>  fix userInfo api & add ChangeGenre

src/controllers/user.controller.js, src/dtos/user.dto.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
add ChangeArtist api
#️⃣연관된 이슈
#15  add ChangeArtist api
📝유저의 name과 email을 값을 이용해 해당 유저를 찾고
유저의 아티스트의 장르 번호 입력 받아 바꾸는 api
[사용 전]
치멘4의 userId -> 4
artistId -> 1
[사용 후]
치멘4의 userId -> 4
artistId -> 2
💬리뷰 요구사항
=> add ChangeArtist api

src/controllers/user.controller.js, src/dtos/user.dto.js, src/repositories/user.repository.js
add swagger
#️⃣연관된 이슈
#17  add swagger
📝 swagger 추가
=> add swagger

src/controllers/music.controller.js, src/index.js
- music.controller.js 추가
- 음악 관련 swagger 추가
=> add music swagger

package-lock.json, package.json, src/auth.config.js, src/controllers/music.controller.js, src/controllers/user.controller.js, src/dtos/music.dto.js, src/index.js, src/lastfm.js, src/repositories/music.repository.js, src/services/music.service.js
- npm 설치 ( lastfmapi, lrclib-api, spotify-web-api-node )
- spotify 로그인 구현
- 노래 정보 가져오기 구현
- 앨범 정보 가져오기 구현
- 아티스트 정보 가져오기 구현
- swagger tag 입력
- music controller swagger 200 응답 수정
=> [feature] 정보 가져오기

src/middleware/email.js
#️⃣연관된 이슈
#5 
기존에 작업했던 인증 전송 메일을 gmail 프로젝트 전용 메일로 교체
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] Email Auth change gmail

prisma/schema.prisma, src/auth.config.js, src/billboard.js, src/controllers/music.controller.js, src/controllers/user.controller.js, src/index.js, src/itunes.js, src/lastfm.js, src/repositories/music.repository.js, src/services/music.service.js
- spotify api 주석 제거
- 추천곡, 앨범 조회 (연도별)
=> [feature] 추천곡, 앨범 조회 (연도별)

prisma/schema.prisma
=> [feature] 라이브러리 DB 추가

package-lock.json, package.json, src/config/s3.config.js, src/controllers/user.controller.js, src/index.js, src/repositories/s3.repository.js, src/services/user.service.js
=> [feature] 이미지 업로드 api 추가

src/controllers/music.controller.js, src/dtos/music.dto.js, src/index.js, src/lastfm.js, src/repositories/music.repository.js, src/services/music.service.js
검색 기능 포함 (검색 시 반환되는 아티스트는 1개만)
=> get all artists based on genre

src/controllers/user.controller.js, src/dtos/user.dto.js, src/repositories/user.repository.js, src/services/user.service.js
회원가입에 library 추가 및 user swagger 수정 (현재 유저의 사진을 업로드 하는 api swagger에서는 동작안함(postman, curl은 작동))
=> [feature] 회원가입에 library 추가

config/response.status.js, src/controllers/music.controller.js, src/controllers/user.controller.js, src/repositories/s3.repository.js
- swagger 응답 수정
- res.status를 res.send로 변경
=> [feature] swagger 응답 수정

prisma/schema.prisma, src/controllers/user.controller.js, src/dtos/user.dto.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
음악 재생 기록 추가
- userMusic prisma 생성
- index 경로 수정
- 음악 재생 기능 구현
- 이미지 변경에 url 추가
=> [feature] 음악 재생 기록 추가

config/response.status.js, package-lock.json, package.json, src/controllers/user.controller.js, src/middleware/gpt.js, src/repositories/user.repository.js
#️⃣연관된 이슈
#52 
스크린샷 (선택)
💬리뷰 요구사항(선택)
여러분 파이팅~
=> [feature] gpt api code

src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#54
- 노래, 앨범 (연도) 추천 기존 로직 방식에서 gpt 적용
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] nomination gpt

src/index.js
#️⃣연관된 이슈
#57 
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] email auth endpoint

src/services/user.service.js
#️⃣연관된 이슈
#57 
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] email auth toString

src/controllers/user.controller.js, src/dtos/user.dto.js, src/index.js, src/repositories/s3.repository.js, src/services/user.service.js
#️⃣연관된 이슈
#61 
- 회원가입 이미지 업로드 통합
- profileUploader upload.single -> upload.fields 형식으로 변환
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 회원가입 이미지 업로드 통합

src/middleware/jwt.js, src/repositories/user.repository.js
jwt payload add
#️⃣연관된 이슈
#65 
jwt token안에 payload에 userId와 AT 인지 RT인지 값을 넣어둠
issuer도 추가함
=> jwt payload add

src/controllers/music.controller.js, src/controllers/user.controller.js
#️⃣연관된 이슈
#68 
회원가입, 추천 음악, 숨겨진 명곡, 노래 정보 가져오기 swagger 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] swagger 수정

package-lock.json, package.json, prisma/migrations/20250129083316_/migration.sql, prisma/schema.prisma, src/controllers/music.controller.js, src/controllers/user.controller.js, src/index.js, src/middleware/jwt.js, src/repositories/music.repository.js, src/services/music.service.js
- npm: prisma 버전 6.2.1로 업데이트
- prisma:
- ArtistCuration 모델 추가 및 Artist description 제거
- AlbumCuration 모델 추가 및 Album description 제거
- GenreImage 모델 추가 및 genre image 제거
- 기타 모델 createdAt, updatedAt 추가
- swagger:
- authorization 설정
- 연도별 추천곡 오류 수정
- 로그인 api requestBody 추가
- 기능 구현
- 앨범 큐레이션, 아티스트 큐레이션 구현 (swagger 문서는 아직입니다.)
- 숨겨진 명곡 일부 앨범 조회 안되는 오류 수정
- 중복된 repository 주석 처리
=> feat:prisma 수정 및 코드 수정

config/response.status.js, src/controllers/user.controller.js, src/dtos/user.dto.js, src/repositories/s3.repository.js, src/services/user.service.js
- swagger: multipart로 작동되게 변경 (기존의 postman에서만 사용 가능했던 문제 해결)
- 이미지 파일이 존재 하지 않을 때와 들어오는 유저 값이 오지 않을 때 에러 추가
=> [feature] 회원가입 수정

src/controllers/music.controller.js, src/index.js, src/repositories/music.repository.js, src/repositories/s3.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#78 
장르 이미지 s3에서 가져오기
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 장르 이미지 s3에서 가져오기

src/controllers/library.controller.js, src/dtos/library.dto.js, src/index.js, src/repositories/library.repository.js, src/services/library.service.js
#️⃣연관된 이슈
#82 
보관함에 저장된 아티스트를 모두 조회하는 api
=> get library artist list

src/controllers/music.controller.js, src/dtos/music.dto.js, src/index.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#85 
music/genre/info에 연결된 controller 코드를 수현님 코드로 수정
기존에 있던 코드 삭제
해당 api에 대한 swagger 문서 작성
=> add swagger docs to get genre img

src/controllers/music.controller.js, src/middleware/jwt.js, src/services/music.service.js
#️⃣연관된 이슈
#88 
swagger 문서 수정
artist 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] swagger 및 코드 수정

src/controllers/library.controller.js, src/dtos/library.dto.js, src/index.js, src/repositories/library.repository.js, src/services/library.service.js
#️⃣연관된 이슈
#87 
보관함에 추가된 앨범 조회하는 API 구현
=> get library album list

src/controllers/music.controller.js
#️⃣연관된 이슈
#93 
user id 받아오는 거 쿼리 스트링에서 bearer 헤더 토큰으로 수정
=> add bearer token to artist info API

src/controllers/music.controller.js, src/dtos/music.dto.js, src/lastfm.js, src/repositories/music.repository.js
#️⃣연관된 이슈
#96 
스웨거에서 쿼리 스트링으로 받는 user id를 헤더로 수정 & 이미지를 lastfm이 아닌 rapid에서 받아오도록 수정
=> modify swagger docs & load artist img

src/controllers/user.controller.js
#️⃣연관된 이슈
#98 
유저 재생 기록 swagger 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 유저 재생 기록 swagger 추가

src/controllers/music.controller.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#100 
연도별 추천 노래 response 앨범 값 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 연도별 추천 노래 수정

src/billboard.js, src/controllers/music.controller.js, src/dtos/music.dto.js, src/services/music.service.js
#️⃣연관된 이슈
#102 
숨겨진 명곡 앨범 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 숨겨진 명곡 앨범 추가

src/controllers/music.controller.js, src/lastfm.js, src/middleware/jwt.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#104 
이름이 중복된 아티스트로 인한 잘못된 이미지 접근 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] 다른 이미지 적용 문제

src/dtos/music.dto.js, src/repositories/music.repository.js, src/services/music.service.js
=> add artist id in response body

prisma/migrations/20250202093747_/migration.sql, src/lastfm.js, src/services/music.service.js
=> [feature] 추천 알고리즘 수정

src/controllers/user.controller.js, src/middleware/gpt.js, src/repositories/user.repository.js, src/services/user.service.js
#️⃣연관된 이슈
#112 
음악 재생에 음악 장르 비동기 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 음악 재생에 음악 장르 비동기 추가

src/controllers/music.controller.js, src/index.js, src/middleware/jwt.js, src/services/music.service.js
#️⃣연관된 이슈
#124 
이 아티스트의 다른 앨범 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 이 아티스트의 다른 앨범

config/response.status.js, src/controllers/music.controller.js, src/index.js, src/middleware/jwt.js, src/services/music.service.js
#️⃣연관된 이슈
#129 
- 노래, 앨범, 아티스트 조회하기
- 개별 조회 가능
스크린샷 (선택)
- 개별 조회 예시
💬리뷰 요구사항(선택)
=> [feature] 모든 정보 조회하기

src/billboard.js, src/dtos/music.dto.js, src/lastfm.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#131 
당신을 위한 곡, 앨범, 숨겨진 명곡 코드 개선
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 당신을 위한 곡, 앨범, 숨겨진 명곡 코드 개선

src/lastfm.js, src/services/music.service.js
#️⃣연관된 이슈
#134 
album mbid 값 artist mbid로 변경
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] mbid 값 수정

package-lock.json, package.json, src/repositories/s3.repository.js
#️⃣연관된 이슈
#136 
- history image s3 업로드 링크 반환 구현
- axios npm 설치
메인 cd 예시
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] history image s3

src/controllers/music.controller.js, src/index.js
#️⃣연관된 이슈
#138 
"/" 경로 swagger ignore 추가
이 아티스트와 비슷한 아티스트 swagger 추가
이 아티스트의 다른 앨범 swagger 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] swagger 작성

src/controllers/music.controller.js, src/index.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#141 
- 빠른 선곡 추가
- listRecommandBasicArtist 값 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 빠른 선곡 추가

src/controllers/music.controller.js, src/services/music.service.js
#️⃣연관된 이슈
#143 
similar artist 응답 값 앨범 추가
swagger 작성
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] similar artist 응답 값 앨범 추가

src/dtos/user.dto.js, src/repositories/user.repository.js, src/services/user.service.js
fix profileImageApi
#️⃣연관된 이슈
#115 
=> fix profileImageApi

src/repositories/user.repository.js
fix timehistory api
#️⃣연관된 이슈
#147 
=> fix timehistory api

src/controllers/user.controller.js, src/itunes.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#153 
앨범 조회 아이튠즈 제거
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] 앨범 조회 아이튠즈 제거

src/controllers/user.controller.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
add user recent music & fix timehistory
#️⃣연관된 이슈
#149 
=> add user recent music & fix timehistory

src/controllers/user.controller.js, src/dtos/user.dto.js, src/repositories/user.repository.js, src/services/user.service.js
fix user swagger & fix profile api
#️⃣연관된 이슈
#156 
users api swagger 수정
profile image api 수정 및 swagger 수정
=> fix user swagger & fix profile api

src/controllers/library.controller.js
#️⃣연관된 이슈
library swagger 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] library swagger 수정

src/controllers/user.controller.js, src/index.js, src/repositories/user.repository.js, src/services/user.service.js
#️⃣연관된 이슈
#168 
유저 프로필 변경 닉네임 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] 유저 프로필 변경 닉네임 수정

src/repositories/s3.repository.js
#️⃣연관된 이슈
#170
장르 정보 앞에 대문자 처리
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] 장르 정보 앞에 대문자 처리

src/controllers/user.controller.js, src/repositories/user.repository.js, src/services/music.service.js
fix user play
#️⃣연관된 이슈
#178 
updatedAt 정렬 가능
=> fix user play

src/controllers/music.controller.js, src/index.js, src/repositories/music.repository.js, src/services/music.service.js
#️⃣연관된 이슈
#176 
- main cd 제작 및 artist 오류 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] main cd 제작 및 artist 오류 수정

src/controllers/user.controller.js, src/repositories/user.repository.js, src/services/user.service.js
fix user play & recent api
swagger all fix
#️⃣연관된 이슈
#183 
user play api
기존에 musicId만 가져오는 기능이였지만
이번에는 musicId를 통해서 음악의 전체적인 정보와 아티스트의 정보도 가져오도록 수정하였다..
user recent api
기존에는 musicartist 배열에 artist 배열에 name 데이터가 있었다면 
music 배열에 artist 배열이 있도록 수정하였다.
=> fix user play & recent api

src/controllers/user.controller.js, src/index.js, src/repositories/user.repository.js
#️⃣연관된 이슈
/users/recent, /users/play 앨범 타이틀 추가
스크린샷 (선택)
- GET /users/play
- GET /users/recent
💬리뷰 요구사항(선택)
=> [feature] 앨범 타이틀 추가 

src/controllers/user.controller.js, src/index.js, src/repositories/user.repository.js
#️⃣연관된 이슈
#187 
GET /users/play
releaseTime 추가
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [feature] releaseTime 추가

prisma/schema.prisma, src/controllers/library.controller.js, src/dtos/library.dto.js, src/index.js, src/repositories/library.repository.js
#️⃣연관된 이슈
#189 
- 보관함 음악 조회에 앨범 추가
- 보관함 아티스트 조회에 앨범 추가
스크린샷 (선택)
음악
아티스트
💬리뷰 요구사항(선택)
=> [feature] 보관함에 앨범 추가

src/controllers/library.controller.js, src/controllers/music.controller.js, src/controllers/user.controller.js, src/dtos/library.dto.js, src/dtos/user.dto.js, src/middleware/jwt.js, src/repositories/library.repository.js, src/repositories/music.repository.js, src/repositories/user.repository.js, src/services/library.service.js, src/services/user.service.js
=> cleanup api

src/repositories/user.repository.js
fix play api
중복된 musicId를 가지고 있다면 가장 최근 updateAt을 가진
musicId 정보 1개만을 가져오도록 수정함.
#202
=> fix play api

src/services/music.service.js
#️⃣연관된 이슈
#206 
숨겨진 명곡 오류 수정
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] 숨겨진 명곡 오류 수정

src/services/music.service.js
#️⃣연관된 이슈
#210 
메인 cd s3업로드 문제 
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [fix] 메인 cd s3업로드 문제 

src/services/music.service.js
#️⃣연관된 이슈
#214 
📝작업 내용
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
당신을 위한 곡 앨범 개수
스크린샷 (선택)
💬리뷰 요구사항(선택)
=> [refactor] 당신을 위한 곡 앨범 개수
